### ISSUE TITLE
Load exception

### ISSUE THREAD

**Issue by vladimirrim** [RamSaw/SoftwareDesign#10]
Loading when no map available

Expected behaviour: Nothing happens

Actual behaiour: 
```
 Exception in thread "main" ru.hse.spb.model.FailedLoadException: Failed to load save file.
	at ru.hse.spb.model.WorldModel.load(WorldModel.kt:201)
	at ru.hse.spb.actions.LoadGameAction.execute(LoadGameAction.kt:7)
	at ru.hse.spb.controller.Controller.run(Controller.kt:40)
	at ru.hse.spb.RoguelikeSinglePlayerApplication.start(RoguelikeSinglePlayerApplication.kt:16)
	at ru.hse.spb.client.RoguelikeClient$Companion.main(RoguelikeClient.kt:104)
	at ru.hse.spb.client.RoguelikeClient.main(RoguelikeClient.kt)
 ```

**Comment by RamSaw** [comment]
Fixed. 
In single player mode works well.
But actually in multiplayer, it is a quite strange thing and sometimes it could lead to strange behavior.
I think there 2 possible solutions:
1. Wipe out support for loading/saving in multiplayer mode.
2. Ignore strange situations and let players be responsible for using multiplayer savings correctly.

I think the second variant is quite good and reasonable and we can follow this way.

**Comment by vladimirrim** [comment]
Allright thank you
