### ISSUE TITLE
Exception whn connecting to session where all players leaved

### ISSUE THREAD

**Issue by vladimirrim** [RamSaw/SoftwareDesign#13]
Expected: Connection to session
Actual:
```
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@1200379
io.grpc.StatusRuntimeException: CANCELLED: call already cancelled
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.stub.ServerCalls$ServerCallStreamObserverImpl.onNext(ServerCalls.java:339)
	at ru.hse.spb.server.RoguelikeServer$ConnectionSetUpperImpl.sendModelToAllPlayers(RoguelikeServer.kt:57)
	at ru.hse.spb.server.RoguelikeServer$ConnectionSetUpperImpl.access$sendModelToAllPlayers(RoguelikeServer.kt:51)
	at ru.hse.spb.server.RoguelikeServer$ConnectionSetUpperImpl$communicate$1.onNext(RoguelikeServer.kt:80)
	at ru.hse.spb.server.RoguelikeServer$ConnectionSetUpperImpl$communicate$1.onNext(RoguelikeServer.kt:62)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onMessage(ServerCalls.java:249)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:297)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:738)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by RamSaw** [comment]
Tried to reproduce but failed.
I did the following:
Connected two players to session, then played a little bit for them, then exitied for both of them. Then I ran one more client and connected to the same session and all was ok.
Please, @vladimirrim give me more information to reproduce this bug.

**Comment by vladimirrim** [comment]
Bug appears when you leave by killing client process. Quiting game through button q is fine.
